### ISSUE TITLE
[Suggestion] Building Skill

### ISSUE THREAD

**Issue by yepidoodles** [Daniel12321/AdventureMMO#30]
This has probably been suggested in the past but I thought I'd mention it anyway.

New Skill - Building

Experience earned from placing certain blocks such as planks and bricks, they'd have to be very low amounts of xp, but would be a cool new skill to have.

**Comment by Daniel12321** [comment]
Thanks for the suggestion. I feel a little stupid for never thinking of it myself, and nobody has ever suggested it before. Ill most likely implement this somewhere in the next week or 2.

**Comment by ghost** [comment]
what purpose could this skill have? after all it shouldn't just be a counter of how many blocks you placed.

the only not out of place yet useful thing i can think of right now, would be something like an ability to harden all blocks you place while your ability is active (maybe a couple of minutes time, or the ability could be limited by the amount of blocks you place and not time.)
those hardened blocks could then take longer to break by players. this would however require that everytime such a hardened block is set, the plugin has to remember it and i'm not sure if there's any good way for checking for hardened blocks without having the plugin check every block that gets broken..

**Comment by zerafox** [comment]
I can't help but agree with @KevinAT here. What purpose does this serve? Just a counter how much you actually build? XD
An alternative, would to turn this into a "crafting" skill. Where crafting certain blocks would increase this skill and give you a chance at crafting an increased number of them.
For example, instead of getting 4 plank blocks from a log, at a certain point you could get 5 and so on and so forth.

So rather than "place a block and build random junk", you're gaining skill for crafting the blocks used to build instead.

**Comment by yepidoodles** [comment]
Who said it had to have a purpose? One of the main functions of AdventureMMO is to compete with your friends, at the moment that's literally all it's doing on my servers (Had to disable skills due to the enchant issue)

**Comment by yepidoodles** [comment]
Closing due to being abandoned.
